  NGINX:
    image: nginx
    links:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  flask:
    restart: always
    build: ./flask_app
    links:
      - database_backup
    ports:
      - 8100:5000
    volumes_from:
      - database_backup
    command: "app.py"
  database_backup:
    image: postgres
    volumes:
      - /var/run/postgresql
    volumes_from:
      - data
    expose:
      - "5432"
  data:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    command: "sleep infinity"